/*----------------------------------------------------------------------
 * This file is generated by mk_parser_show.py.
 *----------------------------------------------------------------------*/
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include "cparser.h"
#include "cparser_priv.h"
#include "cparser_token.h"
#include "cparser_show_tree.h"

cparser_result_t
cparser_glue_show_protect_engine_work_mode (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_protect_engine_work_mode(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_work_mode_online_bridge_proxy (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_protect_engine_work_mode_online_bridge_proxy(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_work_mode_online_route_proxy (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_protect_engine_work_mode_online_route_proxy(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_work_mode_online_reverse_proxy (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_protect_engine_work_mode_online_reverse_proxy(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_work_mode_offline (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_protect_engine_work_mode_offline(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_encode (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_protect_engine_encode(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_ip_black_list (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_protect_engine_ip_black_list(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_ip_white_list (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_protect_engine_ip_white_list(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_url_black_list (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_protect_engine_url_black_list(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_url_white_list (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_protect_engine_url_white_list(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_security_policy (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_protect_engine_security_policy(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_security_policy_detail (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_protect_engine_security_policy_detail(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_security_policy_sp_name_detail (cparser_t *parser)
{
    char *sp_name_val;
    char **sp_name_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[3], &sp_name_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        sp_name_ptr = &sp_name_val;
    };
    cparser_cmd_show_protect_engine_security_policy_sp_name_detail(&parser->context,
        sp_name_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_security_policy_sp_name_type (cparser_t *parser)
{
    char *sp_name_val;
    char **sp_name_ptr = NULL;
    char *type_val;
    char **type_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[3], &sp_name_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        sp_name_ptr = &sp_name_val;
       rc = cparser_get_list(&parser->tokens[4], &type_val);
        if (CPARSER_OK == rc) {
            type_ptr = &type_val;
        } else {
            if (5 <= parser->token_tos) {
                cparser_printf(&parser->context, "Invalid value!\n");
                return CPARSER_OK;
            }
        }
    };
    cparser_cmd_show_protect_engine_security_policy_sp_name_type(&parser->context,
        sp_name_ptr,
        type_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_security_policy_sp_name_type_detail (cparser_t *parser)
{
    char *sp_name_val;
    char **sp_name_ptr = NULL;
    char *type_val;
    char **type_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[3], &sp_name_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        sp_name_ptr = &sp_name_val;
       rc = cparser_get_list(&parser->tokens[4], &type_val);
        if (CPARSER_OK == rc) {
            type_ptr = &type_val;
        } else {
            if (5 <= parser->token_tos) {
                cparser_printf(&parser->context, "Invalid value!\n");
                return CPARSER_OK;
            }
        }
    };
    cparser_cmd_show_protect_engine_security_policy_sp_name_type_detail(&parser->context,
        sp_name_ptr,
        type_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_server_policy (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_protect_engine_server_policy(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_server_policy_detail (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_protect_engine_server_policy_detail(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_server_policy_spname (cparser_t *parser)
{
    char *spname_val;
    char **spname_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[3], &spname_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        spname_ptr = &spname_val;
    };
    cparser_cmd_show_protect_engine_server_policy_spname(&parser->context,
        spname_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_protect_engine_server_policy_spname_detail (cparser_t *parser)
{
    char *spname_val;
    char **spname_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[3], &spname_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        spname_ptr = &spname_val;
    };
    cparser_cmd_show_protect_engine_server_policy_spname_detail(&parser->context,
        spname_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_log_type (cparser_t *parser)
{
    char *log_type_val;
    char **log_type_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_list(&parser->tokens[1], &log_type_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        log_type_ptr = &log_type_val;
    };
    cparser_cmd_show_log_type(&parser->context,
        log_type_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_log_type_recent_hours (cparser_t *parser)
{
    char *log_type_val;
    char **log_type_ptr = NULL;
    uint32_t hours_val;
    uint32_t *hours_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_list(&parser->tokens[1], &log_type_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        log_type_ptr = &log_type_val;
       rc = cparser_get_uint(&parser->tokens[3], &hours_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        hours_ptr = &hours_val;
    };
    cparser_cmd_show_log_type_recent_hours(&parser->context,
        log_type_ptr,
        hours_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day_end_hour_end_min_end_sec (cparser_t *parser)
{
    char *log_type_val;
    char **log_type_ptr = NULL;
    uint32_t start_year_val;
    uint32_t *start_year_ptr = NULL;
    uint32_t start_month_val;
    uint32_t *start_month_ptr = NULL;
    uint32_t start_day_val;
    uint32_t *start_day_ptr = NULL;
    uint32_t start_hour_val;
    uint32_t *start_hour_ptr = NULL;
    uint32_t start_min_val;
    uint32_t *start_min_ptr = NULL;
    uint32_t start_sec_val;
    uint32_t *start_sec_ptr = NULL;
    uint32_t end_year_val;
    uint32_t *end_year_ptr = NULL;
    uint32_t end_month_val;
    uint32_t *end_month_ptr = NULL;
    uint32_t end_day_val;
    uint32_t *end_day_ptr = NULL;
    uint32_t end_hour_val;
    uint32_t *end_hour_ptr = NULL;
    uint32_t end_min_val;
    uint32_t *end_min_ptr = NULL;
    uint32_t end_sec_val;
    uint32_t *end_sec_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_list(&parser->tokens[1], &log_type_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        log_type_ptr = &log_type_val;
       rc = cparser_get_uint(&parser->tokens[3], &start_year_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        start_year_ptr = &start_year_val;
       rc = cparser_get_uint(&parser->tokens[4], &start_month_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        start_month_ptr = &start_month_val;
       rc = cparser_get_uint(&parser->tokens[5], &start_day_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        start_day_ptr = &start_day_val;
       rc = cparser_get_uint(&parser->tokens[6], &start_hour_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        start_hour_ptr = &start_hour_val;
       rc = cparser_get_uint(&parser->tokens[7], &start_min_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        start_min_ptr = &start_min_val;
       rc = cparser_get_uint(&parser->tokens[8], &start_sec_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        start_sec_ptr = &start_sec_val;
       rc = cparser_get_uint(&parser->tokens[10], &end_year_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        end_year_ptr = &end_year_val;
       rc = cparser_get_uint(&parser->tokens[11], &end_month_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        end_month_ptr = &end_month_val;
       rc = cparser_get_uint(&parser->tokens[12], &end_day_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        end_day_ptr = &end_day_val;
       rc = cparser_get_uint(&parser->tokens[13], &end_hour_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        end_hour_ptr = &end_hour_val;
       rc = cparser_get_uint(&parser->tokens[14], &end_min_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        end_min_ptr = &end_min_val;
       rc = cparser_get_uint(&parser->tokens[15], &end_sec_val);
        if (CPARSER_OK != rc) {
            cparser_printf(&parser->context, "Invalid value!\n");
            return CPARSER_OK;
        }
        end_sec_ptr = &end_sec_val;
    };
    cparser_cmd_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day_end_hour_end_min_end_sec(&parser->context,
        log_type_ptr,
        start_year_ptr,
        start_month_ptr,
        start_day_ptr,
        start_hour_ptr,
        start_min_ptr,
        start_sec_ptr,
        end_year_ptr,
        end_month_ptr,
        end_day_ptr,
        end_hour_ptr,
        end_min_ptr,
        end_sec_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_bridge_br_name (cparser_t *parser)
{
    char *br_name_val;
    char **br_name_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[2], &br_name_val);
        if (CPARSER_OK == rc) {
            br_name_ptr = &br_name_val;
        } else {
            if (3 <= parser->token_tos) {
                cparser_printf(&parser->context, "Invalid value!\n");
                return CPARSER_OK;
            }
        }
    };
    cparser_cmd_show_bridge_br_name(&parser->context,
        br_name_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_interface_intf_name (cparser_t *parser)
{
    char *intf_name_val;
    char **intf_name_ptr = NULL;
    cparser_result_t rc;

    if (parser->mode == CPARSER_MODE_CONFIG) {;
       rc = cparser_get_string(&parser->tokens[2], &intf_name_val);
        if (CPARSER_OK == rc) {
            intf_name_ptr = &intf_name_val;
        } else {
            if (3 <= parser->token_tos) {
                cparser_printf(&parser->context, "Invalid value!\n");
                return CPARSER_OK;
            }
        }
    };
    cparser_cmd_show_interface_intf_name(&parser->context,
        intf_name_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_running_config (cparser_t *parser)
{
    if (parser->mode == CPARSER_MODE_CONFIG) {;
    };
    cparser_cmd_show_running_config(&parser->context);
    return CPARSER_OK;
}

cparser_node_t cparser_node_show_running_config_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_running_config,
    "show all configure information",
    NULL,
    NULL
};

cparser_node_t cparser_node_show_running_config = {
    CPARSER_NODE_KEYWORD,
    0,
    "running-config",
    NULL,
    NULL,
    &cparser_node_show_running_config_eol
};

cparser_node_t cparser_node_show_interface_intf_name_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_interface_intf_name,
    "show interface ip information",
    NULL,
    NULL
};

cparser_node_t cparser_node_show_interface_intf_name = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_START | CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:intf_name>",
    NULL,
    NULL,
    &cparser_node_show_interface_intf_name_eol
};

cparser_node_t cparser_node_show_interface_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_show_interface_intf_name,
    NULL,
    &cparser_node_show_interface_intf_name,
    NULL
};

cparser_node_t cparser_node_show_interface = {
    CPARSER_NODE_KEYWORD,
    0,
    "interface",
    NULL,
    &cparser_node_show_running_config,
    &cparser_node_show_interface_eol
};

cparser_node_t cparser_node_show_bridge_br_name_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_bridge_br_name,
    "show bridge information",
    NULL,
    NULL
};

cparser_node_t cparser_node_show_bridge_br_name = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_START | CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:br_name>",
    NULL,
    NULL,
    &cparser_node_show_bridge_br_name_eol
};

cparser_node_t cparser_node_show_bridge_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_show_bridge_br_name,
    NULL,
    &cparser_node_show_bridge_br_name,
    NULL
};

cparser_node_t cparser_node_show_bridge = {
    CPARSER_NODE_KEYWORD,
    0,
    "bridge",
    NULL,
    &cparser_node_show_interface,
    &cparser_node_show_bridge_eol
};

cparser_node_t cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day_end_hour_end_min_end_sec_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day_end_hour_end_min_end_sec,
    "show specified time logs",
    NULL,
    NULL
};

cparser_node_t cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day_end_hour_end_min_end_sec = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:end_sec>",
    NULL,
    NULL,
    &cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day_end_hour_end_min_end_sec_eol
};

cparser_node_t cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day_end_hour_end_min = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:end_min>",
    NULL,
    NULL,
    &cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day_end_hour_end_min_end_sec
};

cparser_node_t cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day_end_hour = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:end_hour>",
    NULL,
    NULL,
    &cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day_end_hour_end_min
};

cparser_node_t cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:end_day>",
    NULL,
    NULL,
    &cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day_end_hour
};

cparser_node_t cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:end_month>",
    NULL,
    NULL,
    &cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month_end_day
};

cparser_node_t cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:end_year>",
    NULL,
    NULL,
    &cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year_end_month
};

cparser_node_t cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time = {
    CPARSER_NODE_KEYWORD,
    0,
    "end-time",
    NULL,
    NULL,
    &cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time_end_year
};

cparser_node_t cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:start_sec>",
    NULL,
    NULL,
    &cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec_end_time
};

cparser_node_t cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:start_min>",
    NULL,
    NULL,
    &cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min_start_sec
};

cparser_node_t cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:start_hour>",
    NULL,
    NULL,
    &cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour_start_min
};

cparser_node_t cparser_node_show_log_type_start_time_start_year_start_month_start_day = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:start_day>",
    NULL,
    NULL,
    &cparser_node_show_log_type_start_time_start_year_start_month_start_day_start_hour
};

cparser_node_t cparser_node_show_log_type_start_time_start_year_start_month = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:start_month>",
    NULL,
    NULL,
    &cparser_node_show_log_type_start_time_start_year_start_month_start_day
};

cparser_node_t cparser_node_show_log_type_start_time_start_year = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:start_year>",
    NULL,
    NULL,
    &cparser_node_show_log_type_start_time_start_year_start_month
};

cparser_node_t cparser_node_show_log_type_start_time = {
    CPARSER_NODE_KEYWORD,
    0,
    "start-time",
    NULL,
    NULL,
    &cparser_node_show_log_type_start_time_start_year
};

cparser_node_t cparser_node_show_log_type_recent_hours_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_log_type_recent_hours,
    "show recent hours logs",
    NULL,
    NULL
};

cparser_node_t cparser_node_show_log_type_recent_hours = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:hours>",
    NULL,
    NULL,
    &cparser_node_show_log_type_recent_hours_eol
};

cparser_node_t cparser_node_show_log_type_recent = {
    CPARSER_NODE_KEYWORD,
    0,
    "recent",
    NULL,
    &cparser_node_show_log_type_start_time,
    &cparser_node_show_log_type_recent_hours
};

cparser_node_t cparser_node_show_log_type_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_log_type,
    "show all logs",
    &cparser_node_show_log_type_recent,
    NULL
};

cparser_list_node_t cparser_list_node_show_log_type_admin_log = {
    NULL,
    "admin-log"
 };

cparser_list_node_t cparser_list_node_show_log_type_access_log = {
    &cparser_list_node_show_log_type_admin_log,
    "access-log"
 };

cparser_list_node_t cparser_list_node_show_log_type_attack_log = {
    &cparser_list_node_show_log_type_access_log,
    "attack-log"
 };

cparser_node_t cparser_node_show_log_type = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_show_log_type_attack_log,
    NULL,
    &cparser_node_show_bridge,
    &cparser_node_show_log_type_eol
};

cparser_node_t cparser_node_show_protect_engine_server_policy_spname_detail_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_server_policy_spname_detail,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_server_policy_spname_detail = {
    CPARSER_NODE_KEYWORD,
    0,
    "detail",
    NULL,
    NULL,
    &cparser_node_show_protect_engine_server_policy_spname_detail_eol
};

cparser_node_t cparser_node_show_protect_engine_server_policy_spname_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_server_policy_spname,
    NULL,
    &cparser_node_show_protect_engine_server_policy_spname_detail,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_server_policy_spname = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:spname>",
    NULL,
    NULL,
    &cparser_node_show_protect_engine_server_policy_spname_eol
};

cparser_node_t cparser_node_show_protect_engine_server_policy_detail_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_server_policy_detail,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_server_policy_detail = {
    CPARSER_NODE_KEYWORD,
    0,
    "detail",
    NULL,
    &cparser_node_show_protect_engine_server_policy_spname,
    &cparser_node_show_protect_engine_server_policy_detail_eol
};

cparser_node_t cparser_node_show_protect_engine_server_policy_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_server_policy,
    "show server policy",
    &cparser_node_show_protect_engine_server_policy_detail,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_server_policy = {
    CPARSER_NODE_KEYWORD,
    0,
    "server-policy",
    NULL,
    NULL,
    &cparser_node_show_protect_engine_server_policy_eol
};

cparser_node_t cparser_node_show_protect_engine_security_policy_sp_name_type_detail_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_security_policy_sp_name_type_detail,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_security_policy_sp_name_type_detail = {
    CPARSER_NODE_KEYWORD,
    0,
    "detail",
    NULL,
    NULL,
    &cparser_node_show_protect_engine_security_policy_sp_name_type_detail_eol
};

cparser_node_t cparser_node_show_protect_engine_security_policy_sp_name_type_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_security_policy_sp_name_type,
    NULL,
    &cparser_node_show_protect_engine_security_policy_sp_name_type_detail,
    NULL
};

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_cc_protect = {
    NULL,
    "cc-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_keyword_filter = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_cc_protect,
    "keyword-filter"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_request_method_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_keyword_filter,
    "request-method-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_protocol_param_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_request_method_protect,
    "protocol-param-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_cookie_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_protocol_param_protect,
    "cookie-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_file_upload_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_cookie_protect,
    "file-upload-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_file_download_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_file_upload_protect,
    "file-download-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_idcard_information_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_file_download_protect,
    "idcard-information-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_magcard_information_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_idcard_information_protect,
    "magcard-information-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_program_code_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_magcard_information_protect,
    "program-code-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_server_error_information_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_program_code_protect,
    "server-error-information-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_creditcard_information_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_server_error_information_protect,
    "creditcard-information-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_http_status_code_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_creditcard_information_protect,
    "http-status-code-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_server_version_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_http_status_code_protect,
    "server-version-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_weak_password_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_server_version_protect,
    "weak-password-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_xml_attack_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_weak_password_protect,
    "xml-attack-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_trojan_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_xml_attack_protect,
    "trojan-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_spider_scanner_attack_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_trojan_protect,
    "spider-scanner-attack-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_directory_index_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_spider_scanner_attack_protect,
    "directory-index-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_path_traversal_attack_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_directory_index_protect,
    "path-traversal-attack-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_misc_attack_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_path_traversal_attack_protect,
    "misc-attack-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_file_include_attack_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_misc_attack_protect,
    "file-include-attack-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_overflow_attack_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_file_include_attack_protect,
    "overflow-attack-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_csrf_attack_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_overflow_attack_protect,
    "csrf-attack-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_xss_attack_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_csrf_attack_protect,
    "xss-attack-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_null_byte_injection_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_xss_attack_protect,
    "null-byte-injection-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_code_injection_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_null_byte_injection_protect,
    "code-injection-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_command_injection_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_code_injection_protect,
    "command-injection-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_email_injection_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_command_injection_protect,
    "email-injection-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_ldap_injection_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_email_injection_protect,
    "ldap-injection-protect"
 };

cparser_list_node_t cparser_list_node_show_protect_engine_security_policy_sp_name_type_sql_injection_protect = {
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_ldap_injection_protect,
    "sql-injection-protect"
 };

cparser_node_t cparser_node_show_protect_engine_security_policy_sp_name_type = {
    CPARSER_NODE_LIST,
    CPARSER_NODE_FLAGS_OPT_START | CPARSER_NODE_FLAGS_OPT_END,
    &cparser_list_node_show_protect_engine_security_policy_sp_name_type_sql_injection_protect,
    NULL,
    NULL,
    &cparser_node_show_protect_engine_security_policy_sp_name_type_eol
};

cparser_node_t cparser_node_show_protect_engine_security_policy_sp_name_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_show_protect_engine_security_policy_sp_name_type,
    NULL,
    &cparser_node_show_protect_engine_security_policy_sp_name_type,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_security_policy_sp_name_detail_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_security_policy_sp_name_detail,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_security_policy_sp_name_detail = {
    CPARSER_NODE_KEYWORD,
    0,
    "detail",
    NULL,
    &cparser_node_show_protect_engine_security_policy_sp_name_eol,
    &cparser_node_show_protect_engine_security_policy_sp_name_detail_eol
};

cparser_node_t cparser_node_show_protect_engine_security_policy_sp_name = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:sp_name>",
    NULL,
    NULL,
    &cparser_node_show_protect_engine_security_policy_sp_name_detail
};

cparser_node_t cparser_node_show_protect_engine_security_policy_detail_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_security_policy_detail,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_security_policy_detail = {
    CPARSER_NODE_KEYWORD,
    0,
    "detail",
    NULL,
    &cparser_node_show_protect_engine_security_policy_sp_name,
    &cparser_node_show_protect_engine_security_policy_detail_eol
};

cparser_node_t cparser_node_show_protect_engine_security_policy_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_security_policy,
    "show security policy",
    &cparser_node_show_protect_engine_security_policy_detail,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_security_policy = {
    CPARSER_NODE_KEYWORD,
    0,
    "security-policy",
    NULL,
    &cparser_node_show_protect_engine_server_policy,
    &cparser_node_show_protect_engine_security_policy_eol
};

cparser_node_t cparser_node_show_protect_engine_url_white_list_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_url_white_list,
    "show url white list",
    NULL,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_url_white_list = {
    CPARSER_NODE_KEYWORD,
    0,
    "url-white-list",
    NULL,
    &cparser_node_show_protect_engine_security_policy,
    &cparser_node_show_protect_engine_url_white_list_eol
};

cparser_node_t cparser_node_show_protect_engine_url_black_list_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_url_black_list,
    "show url black list",
    NULL,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_url_black_list = {
    CPARSER_NODE_KEYWORD,
    0,
    "url-black-list",
    NULL,
    &cparser_node_show_protect_engine_url_white_list,
    &cparser_node_show_protect_engine_url_black_list_eol
};

cparser_node_t cparser_node_show_protect_engine_ip_white_list_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_ip_white_list,
    "show ip white list",
    NULL,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_ip_white_list = {
    CPARSER_NODE_KEYWORD,
    0,
    "ip-white-list",
    NULL,
    &cparser_node_show_protect_engine_url_black_list,
    &cparser_node_show_protect_engine_ip_white_list_eol
};

cparser_node_t cparser_node_show_protect_engine_ip_black_list_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_ip_black_list,
    "show ip black list",
    NULL,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_ip_black_list = {
    CPARSER_NODE_KEYWORD,
    0,
    "ip-black-list",
    NULL,
    &cparser_node_show_protect_engine_ip_white_list,
    &cparser_node_show_protect_engine_ip_black_list_eol
};

cparser_node_t cparser_node_show_protect_engine_encode_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_encode,
    "show encode",
    NULL,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_encode = {
    CPARSER_NODE_KEYWORD,
    0,
    "encode",
    NULL,
    &cparser_node_show_protect_engine_ip_black_list,
    &cparser_node_show_protect_engine_encode_eol
};

cparser_node_t cparser_node_show_protect_engine_work_mode_offline_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_work_mode_offline,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_work_mode_offline = {
    CPARSER_NODE_KEYWORD,
    0,
    "offline",
    NULL,
    NULL,
    &cparser_node_show_protect_engine_work_mode_offline_eol
};

cparser_node_t cparser_node_show_protect_engine_work_mode_online_reverse_proxy_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_work_mode_online_reverse_proxy,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_work_mode_online_reverse_proxy = {
    CPARSER_NODE_KEYWORD,
    0,
    "reverse-proxy",
    NULL,
    NULL,
    &cparser_node_show_protect_engine_work_mode_online_reverse_proxy_eol
};

cparser_node_t cparser_node_show_protect_engine_work_mode_online_route_proxy_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_work_mode_online_route_proxy,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_work_mode_online_route_proxy = {
    CPARSER_NODE_KEYWORD,
    0,
    "route-proxy",
    NULL,
    &cparser_node_show_protect_engine_work_mode_online_reverse_proxy,
    &cparser_node_show_protect_engine_work_mode_online_route_proxy_eol
};

cparser_node_t cparser_node_show_protect_engine_work_mode_online_bridge_proxy_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_work_mode_online_bridge_proxy,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_work_mode_online_bridge_proxy = {
    CPARSER_NODE_KEYWORD,
    0,
    "bridge-proxy",
    NULL,
    &cparser_node_show_protect_engine_work_mode_online_route_proxy,
    &cparser_node_show_protect_engine_work_mode_online_bridge_proxy_eol
};

cparser_node_t cparser_node_show_protect_engine_work_mode_online = {
    CPARSER_NODE_KEYWORD,
    0,
    "online",
    NULL,
    &cparser_node_show_protect_engine_work_mode_offline,
    &cparser_node_show_protect_engine_work_mode_online_bridge_proxy
};

cparser_node_t cparser_node_show_protect_engine_work_mode_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_protect_engine_work_mode,
    "show work mode",
    &cparser_node_show_protect_engine_work_mode_online,
    NULL
};

cparser_node_t cparser_node_show_protect_engine_work_mode = {
    CPARSER_NODE_KEYWORD,
    0,
    "work-mode",
    NULL,
    &cparser_node_show_protect_engine_encode,
    &cparser_node_show_protect_engine_work_mode_eol
};

cparser_node_t cparser_node_show_protect_engine = {
    CPARSER_NODE_KEYWORD,
    0,
    "protect-engine",
    NULL,
    &cparser_node_show_log_type,
    &cparser_node_show_protect_engine_work_mode
};

cparser_node_t cparser_node_show = {
    CPARSER_NODE_KEYWORD,
    0,
    "show",
    NULL,
    NULL,
    &cparser_node_show_protect_engine
};

cparser_node_t cparser_show_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root node of the parser show tree",
    NULL,
    &cparser_node_show
};

