/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#ifndef __CPARSER_TREE_H__
#define __CPARSER_TREE_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

extern cparser_node_t cparser_root;

cparser_result_t cparser_cmd_enable(cparser_context_t *context);
cparser_result_t cparser_cmd_st_write(cparser_context_t *context);
cparser_result_t cparser_cmd_st_load(cparser_context_t *context);
cparser_result_t cparser_cmd_st_configure(cparser_context_t *context);
cparser_result_t cparser_cmd_pe_no_bridge_br_name(cparser_context_t *context,
    char **br_name_ptr);
cparser_result_t cparser_cmd_pe_no_interface_interface_name(cparser_context_t *context,
    char **interface_name_ptr);
cparser_result_t cparser_cmd_pe_no_protect_engine_work_mode(cparser_context_t *context);
cparser_result_t cparser_cmd_pe_no_protect_engine_encode(cparser_context_t *context);
cparser_result_t cparser_cmd_pe_no_protect_engine_security_policy_secpname(cparser_context_t *context,
    char **secpname_ptr);
cparser_result_t cparser_cmd_pe_no_protect_engine_server_policy_serpname(cparser_context_t *context,
    char **serpname_ptr);
cparser_result_t cparser_cmd_pe_bridge_br_name(cparser_context_t *context,
    char **br_name_ptr);
cparser_result_t cparser_cmd_br_interface_interface_name(cparser_context_t *context,
    char **interface_name_ptr);
cparser_result_t cparser_cmd_br_no_interface_interface_name(cparser_context_t *context,
    char **interface_name_ptr);
cparser_result_t cparser_cmd_pe_interface_interface_name_ip_address_ip_address_mask_mask(cparser_context_t *context,
    char **interface_name_ptr,
    uint32_t *ip_address_ptr,
    uint32_t *mask_ptr);
cparser_result_t cparser_cmd_pe_interface_interface_name_up(cparser_context_t *context,
    char **interface_name_ptr);
cparser_result_t cparser_cmd_pe_interface_interface_name_down(cparser_context_t *context,
    char **interface_name_ptr);
cparser_result_t cparser_cmd_pe_protect_engine_work_mode_online_bridge_proxy(cparser_context_t *context);
cparser_result_t cparser_cmd_bridge_proxy_bridge_bridge_name_http_httpport(cparser_context_t *context,
    char **bridge_name_ptr,
    uint32_t *httpport_ptr);
cparser_result_t cparser_cmd_bridge_proxy_bridge_bridge_name_https_httpsport(cparser_context_t *context,
    char **bridge_name_ptr,
    uint32_t *httpsport_ptr);
cparser_result_t cparser_cmd_bridge_proxy_no_bridge_bridge_name_http_httpport(cparser_context_t *context,
    char **bridge_name_ptr,
    uint32_t *httpport_ptr);
cparser_result_t cparser_cmd_bridge_proxy_no_bridge_bridge_name_https_httpsport(cparser_context_t *context,
    char **bridge_name_ptr,
    uint32_t *httpsport_ptr);
cparser_result_t cparser_cmd_bridge_proxy_commit(cparser_context_t *context);
cparser_result_t cparser_cmd_pe_protect_engine_work_mode_online_route_proxy(cparser_context_t *context);
cparser_result_t cparser_cmd_route_proxy_http_httpport(cparser_context_t *context,
    uint32_t *httpport_ptr);
cparser_result_t cparser_cmd_route_proxy_https_httpsport(cparser_context_t *context,
    uint32_t *httpsport_ptr);
cparser_result_t cparser_cmd_route_proxy_no_http_httpport(cparser_context_t *context,
    uint32_t *httpport_ptr);
cparser_result_t cparser_cmd_route_proxy_no_https_httpsport(cparser_context_t *context,
    uint32_t *httpsport_ptr);
cparser_result_t cparser_cmd_route_proxy_commit(cparser_context_t *context);
cparser_result_t cparser_cmd_pe_protect_engine_work_mode_online_reverse_proxy(cparser_context_t *context);
cparser_result_t cparser_cmd_reverse_proxy_ip_address_ipaddr_http_httpport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    uint32_t *httpport_ptr);
cparser_result_t cparser_cmd_reverse_proxy_ip_address_ipaddr_https_httpsport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    uint32_t *httpsport_ptr);
cparser_result_t cparser_cmd_reverse_proxy_no_ip_address_ipaddr_http_httpport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    uint32_t *httpport_ptr);
cparser_result_t cparser_cmd_reverse_proxy_no_ip_address_ipaddr_https_httpsport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    uint32_t *httpsport_ptr);
cparser_result_t cparser_cmd_reverse_proxy_commit(cparser_context_t *context);
cparser_result_t cparser_cmd_pe_protect_engine_work_mode_offline(cparser_context_t *context);
cparser_result_t cparser_cmd_offline_interface_interface_name(cparser_context_t *context,
    char **interface_name_ptr);
cparser_result_t cparser_cmd_offline_no_interface_interface_name(cparser_context_t *context,
    char **interface_name_ptr);
cparser_result_t cparser_cmd_offline_no_ip_address_ipaddr_http_httpport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    uint32_t *httpport_ptr);
cparser_result_t cparser_cmd_offline_no_ip_address_ipaddr_https_httpsport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    uint32_t *httpsport_ptr);
cparser_result_t cparser_cmd_offline_ip_address_ipaddr_http_httpport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    uint32_t *httpport_ptr);
cparser_result_t cparser_cmd_offline_ip_address_ipaddr_https_httpsport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    uint32_t *httpsport_ptr);
cparser_result_t cparser_cmd_offline_commit(cparser_context_t *context);
cparser_result_t cparser_cmd_pe_protect_engine_encode_encoding_type(cparser_context_t *context,
    char **encoding_type_ptr);
cparser_result_t cparser_cmd_pe_protect_engine_ip_black_list(cparser_context_t *context);
cparser_result_t cparser_cmd_ipblack_client_ip_address_ipaddr(cparser_context_t *context,
    uint32_t *ipaddr_ptr);
cparser_result_t cparser_cmd_ipblack_no_client_all(cparser_context_t *context);
cparser_result_t cparser_cmd_ipblack_no_client_ip_address_ipaddr(cparser_context_t *context,
    uint32_t *ipaddr_ptr);
cparser_result_t cparser_cmd_ipblack_no_dynamic_except_all(cparser_context_t *context);
cparser_result_t cparser_cmd_ipblack_no_dynamic_except_ip_address_ipaddr(cparser_context_t *context,
    uint32_t *ipaddr_ptr);
cparser_result_t cparser_cmd_ipblack_no_dynamic_timeout(cparser_context_t *context);
cparser_result_t cparser_cmd_ipblack_dynamic_except_ip_address_ipaddr(cparser_context_t *context,
    uint32_t *ipaddr_ptr);
cparser_result_t cparser_cmd_ipblack_dynamic_timeout_minutes(cparser_context_t *context,
    uint32_t *minutes_ptr);
cparser_result_t cparser_cmd_ipblack_commit(cparser_context_t *context);
cparser_result_t cparser_cmd_pe_protect_engine_ip_white_list(cparser_context_t *context);
cparser_result_t cparser_cmd_ipwhite_client_ip_address_ipaddr(cparser_context_t *context,
    uint32_t *ipaddr_ptr);
cparser_result_t cparser_cmd_ipwhite_no_client_all(cparser_context_t *context);
cparser_result_t cparser_cmd_ipwhite_no_client_ip_address_ipaddr(cparser_context_t *context,
    uint32_t *ipaddr_ptr);
cparser_result_t cparser_cmd_ipwhite_no_server_all(cparser_context_t *context);
cparser_result_t cparser_cmd_ipwhite_no_server_ip_address_ipaddr(cparser_context_t *context,
    uint32_t *ipaddr_ptr);
cparser_result_t cparser_cmd_ipwhite_no_server_host_all(cparser_context_t *context);
cparser_result_t cparser_cmd_ipwhite_no_server_host_plain_text_hostname(cparser_context_t *context,
    char **hostname_ptr);
cparser_result_t cparser_cmd_ipwhite_server_ip_address_ipaddr(cparser_context_t *context,
    uint32_t *ipaddr_ptr);
cparser_result_t cparser_cmd_ipwhite_server_host_plain_text_hostname(cparser_context_t *context,
    char **hostname_ptr);
cparser_result_t cparser_cmd_ipwhite_commit(cparser_context_t *context);
cparser_result_t cparser_cmd_pe_protect_engine_url_black_list(cparser_context_t *context);
cparser_result_t cparser_cmd_urlblack_url_options_url_string(cparser_context_t *context,
    char **options_ptr,
    char **url_string_ptr);
cparser_result_t cparser_cmd_urlblack_no_url_all(cparser_context_t *context);
cparser_result_t cparser_cmd_urlblack_no_url_options_url_string(cparser_context_t *context,
    char **options_ptr,
    char **url_string_ptr);
cparser_result_t cparser_cmd_urlblack_no_dynamic_timeout(cparser_context_t *context);
cparser_result_t cparser_cmd_urlblack_no_dynamic_except_all(cparser_context_t *context);
cparser_result_t cparser_cmd_urlblack_no_dynamic_except_referrer_url_url_string(cparser_context_t *context,
    char **url_string_ptr);
cparser_result_t cparser_cmd_urlblack_dynamic_timeout_minutes(cparser_context_t *context,
    uint32_t *minutes_ptr);
cparser_result_t cparser_cmd_urlblack_dynamic_except_referrer_url_url_string(cparser_context_t *context,
    char **url_string_ptr);
cparser_result_t cparser_cmd_urlblack_commit(cparser_context_t *context);
cparser_result_t cparser_cmd_pe_protect_engine_url_white_list(cparser_context_t *context);
cparser_result_t cparser_cmd_urlwhite_url_options_url_string(cparser_context_t *context,
    char **options_ptr,
    char **url_string_ptr);
cparser_result_t cparser_cmd_urlwhite_no_url_all(cparser_context_t *context);
cparser_result_t cparser_cmd_urlwhite_no_url_options_url_string(cparser_context_t *context,
    char **options_ptr,
    char **url_string_ptr);
cparser_result_t cparser_cmd_urlwhite_commit(cparser_context_t *context);
cparser_result_t cparser_cmd_pe_protect_engine_security_policy_secpname(cparser_context_t *context,
    char **secpname_ptr);
cparser_result_t cparser_cmd_scp_sql_injection_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_sql_injection_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_sql_injection_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_sql_injection_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_sql_keyword_plain_text_keyword(cparser_context_t *context,
    char **keyword_ptr);
cparser_result_t cparser_cmd_sql_no_keyword_all(cparser_context_t *context);
cparser_result_t cparser_cmd_sql_no_keyword_plain_text_keyword(cparser_context_t *context,
    char **keyword_ptr);
cparser_result_t cparser_cmd_scp_weak_password_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_weak_password_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_weak_password_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_weak_password_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_wpd_no_url_all(cparser_context_t *context);
cparser_result_t cparser_cmd_wpd_no_url_type_url_string(cparser_context_t *context,
    char **type_ptr,
    char **url_string_ptr);
cparser_result_t cparser_cmd_wpd_url_type_url_string_password_name_passwordname(cparser_context_t *context,
    char **type_ptr,
    char **url_string_ptr,
    char **passwordname_ptr);
cparser_result_t cparser_cmd_wp_url_weak_password_type_string(cparser_context_t *context,
    char **type_ptr,
    char **string_ptr);
cparser_result_t cparser_cmd_wp_url_no_weak_password_all(cparser_context_t *context);
cparser_result_t cparser_cmd_wp_url_no_weak_password_plain_text_string(cparser_context_t *context,
    char **string_ptr);
cparser_result_t cparser_cmd_wp_url_no_weak_password_regular_exp(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_ldap_injection_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_ldap_injection_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_ldap_injection_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_ldap_injection_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_email_injection_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_email_injection_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_email_injection_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_email_injection_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_command_injection_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_command_injection_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_command_injection_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_command_injection_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_cmd_keyword_plain_text_keyword(cparser_context_t *context,
    char **keyword_ptr);
cparser_result_t cparser_cmd_cmd_no_keyword_all(cparser_context_t *context);
cparser_result_t cparser_cmd_cmd_no_keyword_plain_text_keyword(cparser_context_t *context,
    char **keyword_ptr);
cparser_result_t cparser_cmd_scp_code_injection_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_code_injection_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_code_injection_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_code_injection_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_code_keyword_plain_text_keyword(cparser_context_t *context,
    char **keyword_ptr);
cparser_result_t cparser_cmd_code_no_keyword_all(cparser_context_t *context);
cparser_result_t cparser_cmd_code_no_keyword_plain_text_keyword(cparser_context_t *context,
    char **keyword_ptr);
cparser_result_t cparser_cmd_scp_null_byte_injection_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_null_byte_injection_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_null_byte_injection_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_null_byte_injection_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_xss_attack_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_xss_attack_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_xss_attack_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_xss_attack_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_xss_keyword_plain_text_keyword(cparser_context_t *context,
    char **keyword_ptr);
cparser_result_t cparser_cmd_xss_no_keyword_all(cparser_context_t *context);
cparser_result_t cparser_cmd_xss_no_keyword_plain_text_keyword(cparser_context_t *context,
    char **keyword_ptr);
cparser_result_t cparser_cmd_scp_csrf_attack_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_csrf_attack_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_csrf_attack_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_csrf_attack_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_csrf_cookie_name_plain_text_cookie_name(cparser_context_t *context,
    char **cookie_name_ptr);
cparser_result_t cparser_cmd_csrf_no_cookie_name_all(cparser_context_t *context);
cparser_result_t cparser_cmd_csrf_no_cookie_name_plain_text_cookie_name(cparser_context_t *context,
    char **cookie_name_ptr);
cparser_result_t cparser_cmd_csrf_no_url_all(cparser_context_t *context);
cparser_result_t cparser_cmd_csrf_no_url_type_url_string(cparser_context_t *context,
    char **type_ptr,
    char **url_string_ptr);
cparser_result_t cparser_cmd_csrf_url_type_url_string(cparser_context_t *context,
    char **type_ptr,
    char **url_string_ptr);
cparser_result_t cparser_cmd_scp_overflow_attack_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_overflow_attack_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_overflow_attack_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_overflow_attack_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_file_include_attack_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_file_include_attack_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_file_include_attack_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_file_include_attack_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_misc_attack_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_misc_attack_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_misc_attack_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_misc_attack_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_path_traversal_attack_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_path_traversal_attack_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_path_traversal_attack_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_path_traversal_attack_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_directory_index_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_directory_index_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_directory_index_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_directory_index_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_spider_scanner_attack_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_spider_scanner_attack_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_spider_scanner_attack_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_spider_scanner_attack_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_spider_keyword_plain_text_keyword(cparser_context_t *context,
    char **keyword_ptr);
cparser_result_t cparser_cmd_spider_no_keyword_all(cparser_context_t *context);
cparser_result_t cparser_cmd_spider_no_keyword_plain_text_keyword(cparser_context_t *context,
    char **keyword_ptr);
cparser_result_t cparser_cmd_scp_trojan_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_trojan_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_trojan_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_trojan_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_trojan_keyword_plain_text_keyword(cparser_context_t *context,
    char **keyword_ptr);
cparser_result_t cparser_cmd_trojan_no_keyword_all(cparser_context_t *context);
cparser_result_t cparser_cmd_trojan_no_keyword_plain_text_keyword(cparser_context_t *context,
    char **keyword_ptr);
cparser_result_t cparser_cmd_scp_xml_attack_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_xml_attack_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_xml_attack_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_xml_attack_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_http_status_code_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_http_status_code_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_http_status_code_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_http_status_code_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_server_error_information_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_server_error_information_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_server_error_information_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_server_error_information_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_program_code_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_program_code_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_program_code_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_program_code_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_magcard_information_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_magcard_information_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_magcard_information_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_magcard_information_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_server_version_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_server_version_protect_log_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_server_version_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_server_version_keyword_substitute_plain_text_new_string_for_regular_exp_old_string(cparser_context_t *context,
    char **new_string_ptr,
    char **old_string_ptr);
cparser_result_t cparser_cmd_server_version_no_keyword_all(cparser_context_t *context);
cparser_result_t cparser_cmd_server_version_no_keyword_regular_exp_old_string(cparser_context_t *context,
    char **old_string_ptr);
cparser_result_t cparser_cmd_scp_creditcard_information_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_creditcard_information_protect_log_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_creditcard_information_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_creditcard_keyword_substitute_plain_text_new_string_for_regular_exp_old_string(cparser_context_t *context,
    char **new_string_ptr,
    char **old_string_ptr);
cparser_result_t cparser_cmd_creditcard_no_keyword_all(cparser_context_t *context);
cparser_result_t cparser_cmd_creditcard_no_keyword_regular_exp_old_string(cparser_context_t *context,
    char **old_string_ptr);
cparser_result_t cparser_cmd_scp_idcard_information_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_idcard_information_protect_log_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_idcard_information_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_idcard_keyword_substitute_plain_text_new_string_for_regular_exp_old_string(cparser_context_t *context,
    char **new_string_ptr,
    char **old_string_ptr);
cparser_result_t cparser_cmd_idcard_no_keyword_all(cparser_context_t *context);
cparser_result_t cparser_cmd_idcard_no_keyword_regular_exp_old_string(cparser_context_t *context,
    char **old_string_ptr);
cparser_result_t cparser_cmd_scp_file_download_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_file_download_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_file_download_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_file_download_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_filedown_file_type_plain_text_extension_string(cparser_context_t *context,
    char **extension_string_ptr);
cparser_result_t cparser_cmd_filedown_no_file_type_all(cparser_context_t *context);
cparser_result_t cparser_cmd_filedown_no_file_type_plain_text_extension_string(cparser_context_t *context,
    char **extension_string_ptr);
cparser_result_t cparser_cmd_scp_file_upload_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_file_upload_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_file_upload_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_file_upload_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_fileup_file_type_plain_text_extension_string(cparser_context_t *context,
    char **extension_string_ptr);
cparser_result_t cparser_cmd_fileup_no_file_type_all(cparser_context_t *context);
cparser_result_t cparser_cmd_fileup_no_file_type_plain_text_extension_string(cparser_context_t *context,
    char **extension_string_ptr);
cparser_result_t cparser_cmd_fileup_no_individual_file_size(cparser_context_t *context);
cparser_result_t cparser_cmd_fileup_no_all_file_size(cparser_context_t *context);
cparser_result_t cparser_cmd_fileup_individual_file_size_number(cparser_context_t *context,
    uint32_t *number_ptr);
cparser_result_t cparser_cmd_fileup_all_file_size_number(cparser_context_t *context,
    uint32_t *number_ptr);
cparser_result_t cparser_cmd_scp_cookie_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_cookie_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_cookie_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_cookie_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_cookie_cookie_name_plain_text_extension_string(cparser_context_t *context,
    char **extension_string_ptr);
cparser_result_t cparser_cmd_cookie_no_cookie_name_all(cparser_context_t *context);
cparser_result_t cparser_cmd_cookie_no_cookie_name_plain_text_extension_string(cparser_context_t *context,
    char **extension_string_ptr);
cparser_result_t cparser_cmd_cookie_no_expire_time(cparser_context_t *context);
cparser_result_t cparser_cmd_cookie_no_verification(cparser_context_t *context);
cparser_result_t cparser_cmd_cookie_no_attribution(cparser_context_t *context);
cparser_result_t cparser_cmd_cookie_expire_time_minutes(cparser_context_t *context,
    uint32_t *minutes_ptr);
cparser_result_t cparser_cmd_cookie_verification_method_method_content_type(cparser_context_t *context,
    char **method_ptr,
    char **type_ptr);
cparser_result_t cparser_cmd_cookie_attribution_secure(cparser_context_t *context);
cparser_result_t cparser_cmd_cookie_attribution_secure_httponly(cparser_context_t *context);
cparser_result_t cparser_cmd_cookie_attribution_httponly(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_protocol_param_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_protocol_param_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_protocol_param_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_protocol_param_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_protocol_request_header_num_number(cparser_context_t *context,
    uint32_t *number_ptr);
cparser_result_t cparser_cmd_protocol_request_header_num(cparser_context_t *context);
cparser_result_t cparser_cmd_protocol_no_request_header_num(cparser_context_t *context);
cparser_result_t cparser_cmd_protocol_no_header_size_except_cookie(cparser_context_t *context);
cparser_result_t cparser_cmd_protocol_no_cookie_size(cparser_context_t *context);
cparser_result_t cparser_cmd_protocol_no_request_url_size(cparser_context_t *context);
cparser_result_t cparser_cmd_protocol_no_query_string_size(cparser_context_t *context);
cparser_result_t cparser_cmd_protocol_no_request_argument_name_size(cparser_context_t *context);
cparser_result_t cparser_cmd_protocol_no_request_argument_name_value_size(cparser_context_t *context);
cparser_result_t cparser_cmd_protocol_no_request_argument_num(cparser_context_t *context);
cparser_result_t cparser_cmd_protocol_no_request_body_size(cparser_context_t *context);
cparser_result_t cparser_cmd_protocol_header_size_except_cookie_number(cparser_context_t *context,
    uint32_t *number_ptr);
cparser_result_t cparser_cmd_protocol_cookie_size_number(cparser_context_t *context,
    uint32_t *number_ptr);
cparser_result_t cparser_cmd_protocol_request_url_size_number(cparser_context_t *context,
    uint32_t *number_ptr);
cparser_result_t cparser_cmd_protocol_query_string_size_number(cparser_context_t *context,
    uint32_t *number_ptr);
cparser_result_t cparser_cmd_protocol_request_argument_name_size_number(cparser_context_t *context,
    uint32_t *number_ptr);
cparser_result_t cparser_cmd_protocol_request_argument_name_value_size_number(cparser_context_t *context,
    uint32_t *number_ptr);
cparser_result_t cparser_cmd_protocol_request_argument_num_number(cparser_context_t *context,
    uint32_t *number_ptr);
cparser_result_t cparser_cmd_protocol_request_body_size_number(cparser_context_t *context,
    uint32_t *number_ptr);
cparser_result_t cparser_cmd_scp_request_method_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_request_method_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_request_method_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_request_method_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_method_method_plain_text_method(cparser_context_t *context,
    char **method_ptr);
cparser_result_t cparser_cmd_method_no_method_all(cparser_context_t *context);
cparser_result_t cparser_cmd_method_no_method_plain_text_method(cparser_context_t *context,
    char **method_ptr);
cparser_result_t cparser_cmd_scp_keyword_filter(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_keyword_filter_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_keyword_filter_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_keyword_filter_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_keyword_filter_keyword_plain_text_keyword(cparser_context_t *context,
    char **keyword_ptr);
cparser_result_t cparser_cmd_keyword_filter_no_keyword_all(cparser_context_t *context);
cparser_result_t cparser_cmd_keyword_filter_no_keyword_plain_text_keyword(cparser_context_t *context,
    char **keyword_ptr);
cparser_result_t cparser_cmd_scp_cc_protect(cparser_context_t *context);
cparser_result_t cparser_cmd_scp_cc_protect_action_action_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_cc_protect_action_action_log_option(cparser_context_t *context,
    char **action_ptr,
    char **option_ptr);
cparser_result_t cparser_cmd_scp_cc_protect_option(cparser_context_t *context,
    char **option_ptr);
cparser_result_t cparser_cmd_cc_no_source_ip_access_rate(cparser_context_t *context);
cparser_result_t cparser_cmd_cc_no_source_ip_status_408_rate(cparser_context_t *context);
cparser_result_t cparser_cmd_cc_no_referrer_url_access_rate(cparser_context_t *context);
cparser_result_t cparser_cmd_cc_source_ip_access_rate_statistic_cycle_seconds_request_times_times(cparser_context_t *context,
    uint32_t *seconds_ptr,
    uint32_t *times_ptr);
cparser_result_t cparser_cmd_cc_source_ip_status_408_rate_statistic_cycle_seconds_response_times_times(cparser_context_t *context,
    uint32_t *seconds_ptr,
    uint32_t *times_ptr);
cparser_result_t cparser_cmd_cc_referrer_url_access_rate_statistic_cycle_seconds_request_times_times(cparser_context_t *context,
    uint32_t *seconds_ptr,
    uint32_t *times_ptr);
cparser_result_t cparser_cmd_cc_url_page(cparser_context_t *context);
cparser_result_t cparser_cmd_cc_url_access_rate_statistic_cycle_seconds_request_times_times(cparser_context_t *context,
    uint32_t *seconds_ptr,
    uint32_t *times_ptr);
cparser_result_t cparser_cmd_cc_url_no_access_rate_statistic_cycle(cparser_context_t *context);
cparser_result_t cparser_cmd_cc_url_no_url_all(cparser_context_t *context);
cparser_result_t cparser_cmd_cc_url_no_url_type_url_string(cparser_context_t *context,
    char **type_ptr,
    char **url_string_ptr);
cparser_result_t cparser_cmd_cc_url_url_type_url_string(cparser_context_t *context,
    char **type_ptr,
    char **url_string_ptr);
cparser_result_t cparser_cmd_scp_commit(cparser_context_t *context);
cparser_result_t cparser_cmd_pe_protect_engine_server_policy_serpname(cparser_context_t *context,
    char **serpname_ptr);
cparser_result_t cparser_cmd_sp_deploy_security_policy_secpname(cparser_context_t *context,
    char **secpname_ptr);
cparser_result_t cparser_cmd_sp_no_virt_server_ip_address_ipaddr_https_port(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    uint32_t *port_ptr);
cparser_result_t cparser_cmd_sp_no_virt_server_ip_address_ipaddr_http_port(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    uint32_t *port_ptr);
cparser_result_t cparser_cmd_sp_no_real_server_ip_address_ipaddr_http_httpport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    uint32_t *httpport_ptr);
cparser_result_t cparser_cmd_sp_no_real_server_ip_address_ipaddr_host_hostname_http_httpport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    char **hostname_ptr,
    uint32_t *httpport_ptr);
cparser_result_t cparser_cmd_sp_no_real_server_ip_address_ipaddr_host_hostname_https_httpport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    char **hostname_ptr,
    uint32_t *httpport_ptr);
cparser_result_t cparser_cmd_sp_no_real_server_ip_address_ipaddr_https_httpsport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    uint32_t *httpsport_ptr);
cparser_result_t cparser_cmd_sp_no_access_log_enable(cparser_context_t *context);
cparser_result_t cparser_cmd_sp_no_attack_log_enable(cparser_context_t *context);
cparser_result_t cparser_cmd_sp_no_engine(cparser_context_t *context);
cparser_result_t cparser_cmd_sp_virt_server_ip_address_virt_ipaddr_http_virt_httpport_real_server_ip_address_real_ipaddr_http_real_httpport(cparser_context_t *context,
    uint32_t *virt_ipaddr_ptr,
    uint32_t *virt_httpport_ptr,
    uint32_t *real_ipaddr_ptr,
    uint32_t *real_httpport_ptr);
cparser_result_t cparser_cmd_sp_virt_server_ip_address_virt_ipaddr_https_virt_httpsport_real_server_ip_address_real_ipaddr_https_real_httpsport(cparser_context_t *context,
    uint32_t *virt_ipaddr_ptr,
    uint32_t *virt_httpsport_ptr,
    uint32_t *real_ipaddr_ptr,
    uint32_t *real_httpsport_ptr);
cparser_result_t cparser_cmd_sp_real_server_ip_address_ipaddr_host_hostname_http_httpport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    char **hostname_ptr,
    uint32_t *httpport_ptr);
cparser_result_t cparser_cmd_sp_real_server_ip_address_ipaddr_host_hostname_https_httpsport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    char **hostname_ptr,
    uint32_t *httpsport_ptr);
cparser_result_t cparser_cmd_sp_real_server_ip_address_ipaddr_http_httpport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    uint32_t *httpport_ptr);
cparser_result_t cparser_cmd_sp_real_server_ip_address_ipaddr_https_httpsport(cparser_context_t *context,
    uint32_t *ipaddr_ptr,
    uint32_t *httpsport_ptr);
cparser_result_t cparser_cmd_sp_advanced_configure(cparser_context_t *context);
cparser_result_t cparser_cmd_advance_argument_separator_character(cparser_context_t *context,
    char **character_ptr);
cparser_result_t cparser_cmd_advance_no_argument_separator(cparser_context_t *context);
cparser_result_t cparser_cmd_advance_no_cookie_format(cparser_context_t *context);
cparser_result_t cparser_cmd_advance_cookie_format_version(cparser_context_t *context,
    char **version_ptr);
cparser_result_t cparser_cmd_sp_access_log_enable(cparser_context_t *context);
cparser_result_t cparser_cmd_sp_attack_log_enable(cparser_context_t *context);
cparser_result_t cparser_cmd_sp_attack_log_enable_severity_level(cparser_context_t *context,
    uint32_t *level_ptr);
cparser_result_t cparser_cmd_sp_engine_detect_type(cparser_context_t *context,
    char **detect_type_ptr);
cparser_result_t cparser_cmd_sp_commit(cparser_context_t *context);
cparser_result_t cparser_cmd_st_clear_log_log_type(cparser_context_t *context,
    char **log_type_ptr);
cparser_result_t cparser_cmd_st_clear_url_black_list_dynamic_all(cparser_context_t *context);
cparser_result_t cparser_cmd_st_clear_url_black_list_dynamic_referrer_url_url_string(cparser_context_t *context,
    char **url_string_ptr);
cparser_result_t cparser_cmd_st_clear_ip_black_list_dynamic_all(cparser_context_t *context);
cparser_result_t cparser_cmd_st_clear_ip_black_list_dynamic_ip_address_ipaddr(cparser_context_t *context,
    uint32_t *ipaddr_ptr);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* __CPARSER_TREE_H__ */
